### ISSUE TITLE
How to deploy InternVL?

### ISSUE THREAD

**Issue by Iven2132** [OpenGVLab/InternVL#122]
Great work building InternVL, I'm looking to deploy its inference as an endpoint. I wonder if anyon could help me with that. vLLM and TGI don't support that. What's your suggestion? Please let me know.

**Comment by utkarsh995** [comment]
Check https://github.com/InternLM/lmdeploy/pull/1490

**Comment by Iven2132** [comment]
> Check [InternLM/lmdeploy#1490](https://github.com/InternLM/lmdeploy/pull/1490)

check https://github.com/InternLM/lmdeploy/issues/1495#:~:text=Also%2C%20I%20got,the%20chat%20template.

**Comment by lvhan028** [comment]
LMDeploy v0.4.1 can help deploying InternVL. 
This is a guide https://github.com/OpenGVLab/InternVL/pull/152

**Comment by lvhan028** [comment]
When deploying VLMs on GPUs with limited memory, such as the V100 and T4, it is typically essential to utilize multiple GPUs because of the large size of the model.

Although LMDeploy provides robust support for the LLM part of the VLM model on multiple GPUs, it allocates the entire vision part of the VLM model on the 0-th GPU by default. This allocation can lead to insufficient memory for the LLM part on the 0-th GPU, potentially impacting the model's functionality.

So, to deploy VLMs on GPUs with constrained memory capacities, we have to figure out a way to split the vision model into small parts and dispatch them to multiple GPUs.

We are working on this feature and will release it by the end of this month. Stay tuned.

**Comment by BIGBALLON** [comment]
@lvhan028  If we only consider model inference, which one is faster, LMDeploy or [swift](https://github.com/modelscope/swift/blob/main/docs/source_en/Multi-Modal/internvl-best-practice.md)?

**Comment by lvhan028** [comment]
I didn't find the inference performance benchmark in swift repo. 

If only considering the LLM part, LMDeploy can achieve 25 RPS using the SharedGPT dataset, which is nearly 2x faster than vLLM.

But LMDeploy didn't optimize the inference of the vision model. Vision model's optimzation is beyond the scope of LMDeploy and we don't have plans to do that.

**Comment by BIGBALLON** [comment]
> When deploying VLMs on GPUs with limited memory, such as the V100 and T4, it is typically essential to utilize multiple GPUs because of the large size of the model.
> 
> Although LMDeploy provides robust support for the LLM part of the VLM model on multiple GPUs, it allocates the entire vision part of the VLM model on the 0-th GPU by default. This allocation can lead to insufficient memory for the LLM part on the 0-th GPU, potentially impacting the model's functionality.
> 
> So, to deploy VLMs on GPUs with constrained memory capacities, we have to figure out a way to split the vision model into small parts and dispatch them to multiple GPUs.
> 
> We are working on this feature and will release it by the end of this month. Stay tuned.

So if it possible to use a single V100(32G) GPU to deploy InternVL-Chat-V1-5-Int8, if so, how do we set the `tp` and k/v cache?

**Comment by G-z-w** [comment]
Hi, you can use LMDeploy or swift. See [LMDeploy](https://github.com/OpenGVLab/InternVL/tree/v2.0.0?tab=readme-ov-file#inference-acceleration-by-lmdeploy) or [swift](https://github.com/modelscope/swift)
