### ISSUE TITLE
why model code on github and huggingface is different??

### ISSUE THREAD

**Issue by dragen1860** [OpenGVLab/InternVL#237]
Hugginceface Version: it has `batch_chat` function！
https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5/blob/main/modeling_internvl_chat.py

![image](https://github.com/OpenGVLab/InternVL/assets/4252555/848c2bd0-de8f-44de-8e09-b4f9c9e858ec)

However, in github, the code is absolutely different( no `batch_chat` at all.).
https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/model/internvl_chat/modeling_internvl_chat.py

![image](https://github.com/OpenGVLab/InternVL/assets/4252555/5fe18426-5238-4f0c-805c-3abd48fe0ccc)

This is reaaly unconvinent since we use github to debug our model but rely on huggingface to download model checkpoint. Anyone give some helpful advices?

**Comment by Weiyun1025** [comment]
Thank you for your interest in our work. Our model has been undergoing rapid iterations and updates. We are about to open-source the training and model code of InternVL2. Please refer to the InternVL2 code at that time. We apologize for any inconvenience caused by the inconsistencies in the previous code versions.
