### ISSUE TITLE
Compare with InternImage on semantic segmentation task?

### ISSUE THREAD

**Issue by chl916185** [OpenGVLab/InternVL#25]
![Snipaste_2024-01-04_11-41-30](https://github.com/OpenGVLab/InternVL/assets/28615358/a0778e69-ef56-475d-8930-31dfb961bfea)

https://github.com/OpenGVLab/InternImage

**Comment by czczup** [comment]
Hello, thank you for your question. Currently, the semantic segmentation performance of InternViT-6B is approximately at a level comparable to InternImage-H. Because the model is quite large, we used a resolution of 504x504 in the experiments with InternViT-6B, without scaling up to 896x896. Additionally, InternImage's pre-training includes supervised signal for mask image modeling, which is beneficial for semantic segmentation, whereas InternVL does not incorporate this feature.

**Comment by chl916185** [comment]
> Hello, thank you for your question.
> 
> Currently, the semantic segmentation performance of InternViT-6B (UperNet + 504x504 = 58.9 mIoU) is approximately comparable to InternImage-H (UperNet + 896x896 = 59.9 mIoU). Because the model is quite large, we used a resolution of 504x504 in the experiments with InternViT-6B, without scaling up to 896x896.
> 
> Additionally, InternImage's pre-training includes supervised signal for mask image modeling, which is beneficial for semantic segmentation, whereas InternVL does not incorporate this feature.

ok, thank you!
@czczup
