### ISSUE TITLE
About the detect dataset in pretrain stage

### ISSUE THREAD

**Issue by zhww** [OpenGVLab/InternVL#315]
In the technical report，Object365 was used for pretrain, but I test mini-4B, it can't do object detection.
So, what the detect data format or instructions are used during pretrain?

**Comment by czczup** [comment]
InternVL 1.5 does not support object detection because we only used object detection data during the pre-training stage and did not utilize it during the SFT stage.

Now, the new InternVL 2.0 series models support object detection. You can try it out in our online demo: https://internvl.opengvlab.com/
