### ISSUE TITLE
If I need to fine-tune internvl2-4b model, which code should I refer to?

### ISSUE THREAD

**Issue by jingcangcang** [OpenGVLab/InternVL#348]

**Comment by VietDunghacker** [comment]
I try finetuning my project using the same codebase with Mini-InternVL (also modify the chat template with the new system message). However the performance of InternVL2-4B is worse than that of Mini-InternVL 4B. No idea what caused the problem.

**Comment by VietDunghacker** [comment]
I use the same code base of Mini-InternVL 1.5 4B, update the chat template to the new version (you can check file conversation.py of the huggingface page). But it seems weird that when I finetuned the model using LoRA, the performance InternVL2-4B is worse than that of MiniInternVL-4B. No clue if I missed something.

**Comment by cxmscb** [comment]
> I use the same code base of Mini-InternVL 1.5 4B, update the chat template to the new version (you can check file conversation.py of the huggingface page). It worked fine without error, but it seems weird that when I finetuned the model using LoRA, the performance of the finetuned InternVL2-4B is worse than the finetuned MiniInternVL-4B (test on 2 different datasets). No clue if I missed something.

Does it support multiple images for finetuning?

**Comment by VietDunghacker** [comment]
The current codebase does not support it yet. But I think can look up the branch nopacking_final. There is some code for interleave data in there, but I don't know if it is final.
By the way I found the reason for worse performance is because I incorrectly merge the finetuned adapter into the old model (InternVL-1.5). Somehow the merged model still work, what a wonder.

**Comment by whai362** [comment]
see here https://github.com/OpenGVLab/InternVL?tab=readme-ov-file
