### ISSUE TITLE
When using demo running Intervl2-8b, the response tend to response the same sentence several times until meets max_token_len

### ISSUE THREAD

**Issue by Arthurwyf** [OpenGVLab/InternVL#366]

**Comment by BryantKai** [comment]
我也遇到了这样的问题

**Comment by MasterJanus** [comment]
same question +1

**Comment by czczup** [comment]
This issue is likely due to noisy data in the previous model’s training set, causing occasional repetition of sentences.  We've trained the new InternVL 2.5 model to reduce this behavior.  I recommend trying it, as it performs more smoothly.  Let me know if you'd like more details or help setting it up.
