### ISSUE TITLE
[Feature] Is InternVL2-1xB in the plan?

### ISSUE THREAD

**Issue by cxmscb** [OpenGVLab/InternVL#404]
### Motivation

There is a missing for InternVL2-1xB models, and is InternVL2-1xB in the plan, e.g., combiming [InternViT‑6B‑448px‑V1‑5](https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5) and [internlm2_5‑7b‑chat](https://huggingface.co/internlm/internlm2_5-7b-chat).

**Comment by czczup** [comment]
Hi, thanks for your advice.

The training of the model you mentioned has been completed, and if open-sourced, it will be named `InternVL2-13B`. The current results are: ViT-6B + InternLM2.5-7B (`InternVL2-13B`) >= ViT-6B + InternLM2-20B (`InternVL2-26B`) > ViT-300M + InternLM2.5-7B (`InternVL2-8B`).

From these results, I draw two conclusions:

1. For the same LLM, InternLM2.5-7B, using entirely fair experimental settings, the performance of ViT-6B is indeed significantly better than ViT-300M, even though the total number of parameters of the model has almost doubled.

2. The performance of InternLM2.5-7B is very close to, or even surpasses in some aspects, that of InternLM2-20B.

The reason I have not released this model yet is due to concerns about providing too many models currently.

**Comment by cxmscb** [comment]
> Hi, thanks for your advice.
> 
> The training of the model you mentioned has been completed, and if open-sourced, it will be named `InternVL2-13B`. The current results are: ViT-6B + InternLM2.5-7B (`InternVL2-13B`) >= ViT-6B + InternLM2-20B (`InternVL2-26B`) > ViT-300M + InternLM2.5-7B (`InternVL2-8B`).
> 
> From these results, I draw two conclusions:
> 
> 1. For the same LLM, InternLM2.5-7B, using entirely fair experimental settings, the performance of ViT-6B is indeed significantly better than ViT-300M, even though the total number of parameters of the model has almost doubled.
> 2. The performance of InternLM2.5-7B is very close to, or even surpasses in some aspects, that of InternLM2-20B.
> 
> The reason I have not released this model yet is due to concerns about providing too many models currently.

Thank you for the consideration and reply! 
1) From my point of view, `InternVL2-13B` is quite necessary, since it will provide much insights for the importances of the vision part and the language part in the vlms.

2) In the evaluation on our data, the performance difference is quite large between `InternVL2-8B` and `InternVL2-26B`, while the performance difference is quite large between `InternVL2-26B` and `InternVL2-40B`. It could indicate the the vision part is more important, and  `InternVL2-13B` could show similar performance with less inference/training cost.

**Comment by czczup** [comment]
Thank you for your advice!

**Comment by alesspalma** [comment]
Hi, are there any news on the release of InternVL2-13B ? I agree with @cxmscb , it would be awesome to have!
