### ISSUE TITLE
Clarification on Commercial Use and API Requirement for internvl2 Models

### ISSUE THREAD

**Issue by vietpho** [OpenGVLab/InternVL#453]
### 📚 The doc issue

Hi,

I have a few questions regarding the commercial use of internvl2 models.

1. From what I understand, internvl2 models, including those used with LLaMA and Qwen that allow commercial use based on user count, are commercially usable, except for LLaVA, which is not. Is that correct?

2. Is it impossible to use internvl2-pro without an API? I want to use it for commercial purposes, not just research.

3. Is it permissible to use internvl2-pro commercially, even if it requires using the API?

Thank you.

**Comment by czczup** [comment]
Hi,

**Commercial Use:** Yes, InternVL2 models, including those with LLaMA and Qwen, are commercially usable (provided that you also comply with their original licenses), except for LLaVA, which is not.

**Using InternVL2-Pro:** InternVL2-Pro has not released its weights, so it can only be accessed via API. Due to our limited deployment resources, we recommend using this API for academic research.

**Commercial Use via API:** Due to our limited deployment resources, we recommend using this API for academic research. For commercial API usage, you can deploy our open-source model weights on your own devices.

**Comment by helq2612** [comment]
Hi,
I have a follow-up question: 
Does the pre-training stage (for InternVL1.5 and InternVL2.0) use some non-commercial datasets?

From InterVL1.5 report, I found in the pre-training stage, it used Wukong-OCR (Table 1.a). However, Wukong dataset does not allow the commercial usage (https://github.com/hanj4096/wukong/blob/master/LICENSE).
