### ISSUE TITLE
 InternVL-Chat-V1.2 continue finetune

### ISSUE THREAD

**Issue by yuan10li20221130** [OpenGVLab/InternVL#47]
Is it possible to finetune on the trained  InternVL-Chat-V1.2 mdoel（https://huggingface.co/OpenGVLab/InternVL-Chat-Chinese-V1-2/tree/main） using a small dataset about 20k，Or I have to train from scratch（using InternViT-6B-448px-V1-2 and Nous-Hermes-2-Yi-34B model） and then finetune it on my small dataset？

**Comment by czczup** [comment]
Hi, thanks for your attention. Of course, you can continue to fine-tune the [InternVL-Chat-V1.2](https://huggingface.co/OpenGVLab/InternVL-Chat-Chinese-V1-2) model.

First, please upgrade to latest code base:
```
git pull
cd internvl_chat/
pip install -e .
```

Then, you should download the pretrained InternVL-Chat-V1.2 model, and for example, put this model at `pretrained/InternVL-Chat-Chinese-V1-2`:
```
cd pretrained/
huggingface-cli download --resume-download --local-dir-use-symlinks False OpenGVLab/InternVL-Chat-Chinese-V1-2 --local-dir InternVL-Chat-Chinese-V1-2
```

Before start fine-tuning, you should prepare your custom training data. Like [this file](internvl_chat/shell/data/data_yi34b_finetune.json), you should write a json file to record the meta information of your custom dataset. Then, you should  set the `--meta_path` to your custom meta file in this [script](./shell/hermes2_yi34b/internvl_chat_v1_2_hermes2_yi34b_448_finetune_continue.sh).

After that, you can use 16 GPUs to fine-tune this model. Due to the 40 billion parameters of this model, we currently do not support fine-tuning with just 8 GPUs (might require using LORA instead of fine-tuning the entire LLM).

```sh
# using 16 GPUs
PARTITION='your partition' GPUS=16 sh shell/hermes2_yi34b/internvl_chat_v1_2_hermes2_yi34b_448_finetune_continue.sh
```

If you encounter any problems, please let me know. Thank you.

**Comment by zhly0** [comment]
Thank you for quick reply!
Since I do not have to much computing power,and my data is small ,is it possible to train it using lora on one or two A100(80G memory) machine?

**Comment by czczup** [comment]
I am currently preparing a LoRa shell script for you. Please hang tight while I get it ready.

**Comment by zhly0** [comment]
Really grateful ! 
Thank you !

**Comment by czczup** [comment]
Hi, you can try to run this script with 2 A100 80G GPUs.

https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/hermes2_yi34b/internvl_chat_v1_2_hermes2_yi34b_448_finetune_continue_lora.sh

In my exp, this script will take about 77G GPU memory in each A100 GPU. 
You can change the `BATCH_SIZE`, `PER_DEVICE_BATCH_SIZE`, `num_train_epochs`, `use_llm_lora`, `max_seq_length` according to your custom dataset.

`use_llm_lora` means the LoRA rank, I set it to 16. And `max_seq_length` means the max length of sequence during training, you can reduce this value if your data is short.

**Comment by yuan10li20221130** [comment]
That's very nice of you！
I will give it a try on the new model.
Thank you！

**Comment by songge25** [comment]
图片可以是url吗
