### ISSUE TITLE
Compare PixelShuffle with Qfromer?

### ISSUE THREAD

**Issue by BlueBlueFF** [OpenGVLab/InternVL#50]
hi, Do you have tried the Qfromer Arch? I think using pixelshuffle is to limit vision token nums and qformer has same effects~

**Comment by czczup** [comment]
The recently released models, including InternVL-Chat-V1.1 and V1.2, adopt pixel shuffle. There hasn't been a comparison done here because pixel shuffle is relatively simple and was used directly. 

If we continue to scale up the resolution, for example, to a size of 896x896, pixel shuffle would result in 1024 image tokens, while Qformer uses a manually set fixed token count. From the perspective of retaining image details, pixel shuffle preserves more detailed information. However, from the standpoint of computational load, Qformer's approach imposes less strain on subsequent LLM computations.

In subsequent experiments where we further increase the resolution, we will ablate these two methods.

**Comment by BlueBlueFF** [comment]
Thans~ One more question, Is A100-80G + Zero 3 is enough for traning full 40B models?  no need for megatron?

**Comment by czczup** [comment]
> Thanks~ One more question, Is A100-80G + Zero 3 is enough for traning full 40B models? no need for megatron?

Yes, you can fine-tune with 32 GPUs for the entire 40B model; Fewer GPUs are needed if you use LORA.
