### ISSUE TITLE
Pre-training on the new cleaned LAION

### ISSUE THREAD

**Issue by ofrimasad** [OpenGVLab/InternVL#562]
### Motivation

Hi.
I saw a new version of the LAION dataset just came out (Aug 30th, 2024). The samples from the CSAM dataset were removed from LAION.
Do you intend to re-train your InternViT models on the new dataset? We can't use the existing model weights because of that data issue.
Could you please expose the InternViT training scripts and recipes so that we can train them on the new LAION dataset? 
Thanks 

### Related resources

https://laion.ai/blog/relaion-5b/

**Comment by czczup** [comment]
Hello, thank you for your attention. Due to limited computational resources, we currently have no plans to retrain our InternViT-6B using the new Re-LAION. Training such a visual encoder from random initialization with billions of image-text pairs is extremely resource-intensive.

Additionally, we did not fully utilize the original LAION-5B dataset. We only used parts of it, specifically LAION-EN and LAION-multi, and directly discarded the entire LAION-nolang portion. After applying our filtering pipeline, the retained data volumes for LAION-EN and LAION-multi were 1.94B and 1.87B, respectively. We discarded approximately 15% of the samples, which I believe may help reduce the potential impact of these potential illegal image samples (CSAM).

Moreover, the first stage of pre-training for InternViT actually adopted the CLIP training scheme, so you can use OpenCLIP for training. Our code is similar to OpenCLIP with added deepspeed support, but due to the lack of code cleaning, we currently have no plans to release this code.
