### ISSUE TITLE
About multiple image input.

### ISSUE THREAD

**Issue by sunanhe** [OpenGVLab/InternVL#73]
I want to continue fine-tuning the model with multiple image inputs. Is there any suggestion about how to implement the multiple images input?

**Comment by czczup** [comment]
Hello, thank you for your attention. 

I think if we want to support multi-image training, the main changes will be in the [dataloader](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L372), such as support for reading multiple images and generating <IMG_CONTEXT> placeholders based on the number of images in the `preprocess_function`.

<img width="893" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/1849a63a-d8bc-41bb-94ea-5a88061162ee">

Because each sample gets an inconsistent number of images after these changes, some changes to the default `data_collator` are also required.

**Comment by sunanhe** [comment]
Thanks for your suggestions.

**Comment by dszpr** [comment]
Hi！Have you solved the multiple image inputs issue?
I want to input nuscenes dataset which input 6 images per sample.
If you have solved this multiple image inputs issue, could you please tell me what and where is the code you change?
Appreciate so much!
