### ISSUE TITLE
Intervl2.5

### ISSUE THREAD

**Issue by LKELN** [OpenGVLab/InternVL#762]
### 📚 The doc issue

Repetition Detection: We use an LLM combined with a specialized prompt to identify repetitive samples. These samples are then subjected to manual review, and those scoring below a threshold (e.g., 3) are removed to maintain data quality.

How do you identify duplicate samples using LLM? Why not use a method like Kmeans clustering for screening? It's very difficult for LLM to handle an entire dataset at one time.

**Comment by yuecao0119** [comment]
Thank you very much for your question.
The following is my personal understanding. We process data in units of samples, and mainly focus on the local situation where words or sentences are repeated. Due to the next word training method of LLM, LLM is more sensitive to the format of this data and is better able to identify repeated problems.
K-means clustering may be more inclined to classify samples with similar features and focus on the overall characteristics of the samples. Therefore, the field to which the samples belong, the information they contain, etc. may interfere with the classification results more.
Of course, this is just my understanding. You can actually test it. Maybe a good clustering processing method is more effective.

**Comment by czczup** [comment]
Hello, perhaps there are some ambiguities in the wording of our technical report. What we actually intend to filter and discard are the repeat patterns within the sample, not the repetitions between samples.

**Comment by LKELN** [comment]
Thanks
