### ISSUE TITLE
InternVl-Chat-V1.5多卡推理报错

### ISSUE THREAD

**Issue by douyh** [OpenGVLab/InternVL#95]
在使用多卡推理的代码的时候，出现了如下错误：
![image](https://github.com/OpenGVLab/InternVL/assets/34704737/6b9a31b7-3db4-48af-b42c-df8e70f56c5c)

使用的代码是https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5 中给的代码

**Comment by lh-seu** [comment]
same question, 单卡跑就没有问题

**Comment by douyh** [comment]
好像并不能解决这个问题。有大佬可以看看吗？

**Comment by cyj95** [comment]
# If you have an 80G A100 GPU, you can put the entire model on a single GPU.
model = AutoModel.from_pretrained(
    path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True).eval().cuda()
# Otherwise, you need to set device_map='auto' to use multiple GPUs for inference.
# model = AutoModel.from_pretrained(
#     path,
#     torch_dtype=torch.bfloat16,
#     low_cpu_mem_usage=True,
#     trust_remote_code=True,
#     device_map='auto').eval()



看注释 这段要改

**Comment by HuangZhen02** [comment]
同样的问题。
感觉是模型device_map='auto'时，这里的self.language_model被部署到了和input_ids不同的gpu上，modeling_internvl_chat.py中的generate函数报错
```
input_embeds = self.language_model.get_input_embeddings()(input_ids)
```

**Comment by douyh** [comment]
> 同样的问题。 感觉是模型device_map='auto'时，这里的self.language_model被部署到了和input_ids不同的gpu上，modeling_internvl_chat.py中的generate函数报错
> 
> ```
> input_embeds = self.language_model.get_input_embeddings()(input_ids)
> ```

看issue96， 在大家的魔改下已经可用了。
